language: python
python:
  - "3.4"

before_install:
  - sudo apt-get update
  - sudo apt-get install pandoc
  - curl -O -L https://github.com/IDPF/epubcheck/releases/download/v3.0/epubcheck-3.0.zip && unzip epubcheck-3.0.zip -d ~
#  - curl -o ~/kindlegen http://softcover-binaries.s3.amazonaws.com/kindlegen && chmod +x ~/kindlegen
#  - curl http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz

install:
  - pandoc --version
  - pip install requests markdown beautifulsoup4

script:
  - make build-epub
  - make build-html

notifications:
  email:
    - estetus+travis-ci@gmail.com


